sonar.projectKey=devops-for-cplusplus
sonar.projectName=devops-for-cplusplus
sonar.sources=app/src,app/include
sonar.tests=app/tests
sonar.sourceEncoding=UTF-8
sonar.cfamily.compile-commands=build/compile_commands.json